[0]
Meter=String
MeterStyle=s
Text=Default
LeftMouseDownAction=[!SetVariable AudioDeviceID "" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "" "D:\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Default" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[1]
Meter=String
MeterStyle=s
Text=1 - DELL U2415 (AMD High Definition Audio Device)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{9eca42d9-6620-4aef-8ce3-5b650984ab0a}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{9eca42d9-6620-4aef-8ce3-5b650984ab0a}" "D:\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "1 - DELL U2415 (AMD High Definition Audio Device)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[2]
Meter=String
MeterStyle=s
Text=Speakers (Realtek High Definition Audio)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{ac2ab0c4-b743-4c3b-87f0-c9dc1eaaadbf}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{ac2ab0c4-b743-4c3b-87f0-c9dc1eaaadbf}" "D:\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Speakers (Realtek High Definition Audio)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[3]
Meter=String
MeterStyle=s
Text=Realtek Digital Output (Realtek High Definition Audio)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{ff24fdb0-a99d-4834-8f2f-c3374c3b1129}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{ff24fdb0-a99d-4834-8f2f-c3374c3b1129}" "D:\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Realtek Digital Output (Realtek High Definition Audio)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
